# site settings
title: audiovsn
subtitle: Events in und um Darmstadt
email: youremailaddress@gmail.com
description: Wir machen kuschelige Events in und um Darmstadt. Auf unseren Parties hört ihr frische Musik, handgefertigte Visuals und 3D Audio. Tighte Beats direkt aus der Flasche. Verkauf von Musik und Wasser.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://facebook.com/audiovsn
soundcloud_url: http://soundcloud.com/audiovsn
instagram_url: https://instagram.com/audiovsn


# build settings
markdown: kramdown

sass:
  style: compressed
